use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# HlcupWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :hlcup, HlcupWeb.Endpoint,
  load_from_system_env: false,
  http: [
    ip: {0,0,0,0},
    port: 80,
    acceptors: 150,
    max_connections: :infinity
    # timeout: 2000
    # protocol_options: [{:max_keepalive, 1_000_000},{:timeout, 2000}]
  ],
  url: [host: "travels.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  version: Application.spec(:hlcup, :vsn)

# Do not print debug messages in production
config :logger, level: :error, compile_time_purge_level: :error

config :hlcup, HlcupWeb.Endpoint,
  secret_key_base: "JTzVmIO4/3Kj+XRUT+7EPJfEPztf/wttM1UhoDsPRlu9GrQ4f05Dp+EA9OgvJypz"

# Configure your database
config :hlcup, Hlcup.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "hlcup_prod",
  pool_size: 15
